import re
from transformers import pipeline
import torch

# Global cache for loaded models
_model_cache = {}

def call_api(model, messages, temperature=0.1, max_new_tokens=256, **kwargs):
    """
    Call a local transformers model for inference
    :param model: Model name or path
    :param messages: List of messages
    :param temperature: Generation temperature
    :param max_new_tokens: Maximum number of new tokens to generate
    :param kwargs: Other parameters
    :return: Text generated by the model
    """
    # Determine the model path based on the model name
    if model == "gpt-oss-20b":
        model_path = "/mnt/data/openai/gpt-oss-20b"
    elif model == "gpt-oss-120b":
        model_path = "/mnt/data/openai/gpt-oss-120b"
    else:
        raise ValueError(f"Unsupported model: {model}")

    # Check if model is already loaded in cache
    model_key = f"{model}_{model_path}"
    if model_key not in _model_cache:
        # Create a text generation pipeline
        _model_cache[model_key] = pipeline(
            "text-generation",
            model=model_path,
            torch_dtype="auto",
            device_map="auto",
        )
        print(f"Model {model} loaded and cached.")
    else:
        print(f"Using cached model {model}.")

    # Get the pipeline from cache
    pipe = _model_cache[model_key]

    # Call the model to generate text
    outputs = pipe(
        messages,
        max_new_tokens=max_new_tokens,
        temperature=temperature,
        do_sample=True if temperature > 0 else False,
    )
    
    # Get raw response
    raw_response = outputs[0]["generated_text"][-1]["content"]
    
    return raw_response


if __name__ == "__main__":
    # Example usage
    model = "gpt-oss-20b"
    messages = [
        {"role": "user", "content": "Explain quantum mechanics clearly and concisely."},
    ]
    
    response = call_api(model, messages, max_new_tokens=1024)
    print(response)
